name: Boosty - Boost Your Own Productivity
description: Boosty is an assistant who help you to save time and money!
iOS: https://telegra.ph/Replace-this-link-07-23
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
