name: Boosty - Boost Your Own Productivity
description: Boosty is an assistant who help you to save time and money!
iOS: https://apps.apple.com/app/id6443485441
screenshots:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  - 4.jpg
  - 5.jpg
